### ISSUE TITLE
yarn install does not work

### ISSUE THREAD

**Issue by jpzk** [brinktrade/brink-core#2]
yarn install v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@brinkninja%2ftest-helpers: Not found".

running node v16.2.0

**Comment by mikec** [comment]
@jpzk this is fixed now. switched to use https://github.com/brinktrade/brink-utils instead of the private test-helpers repo which is deprecated
